export const SET_READY = 'SET_READY';
export const RECEIEVE_EXAMPLE_DATA = 'RECEIEVE_EXAMPLE_DATA';
export const REQUEST_DATA = 'REQUEST_DATA';
export const REQUEST_DATA_ERROR = 'REQUEST_DATA_ERROR';
